# Generated by Django 5.1 on 2024-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('sumario', models.CharField(max_length=500)),
                ('fecha_publicacion', models.DateField()),
                ('observaciones', models.CharField(max_length=500)),
                ('origen', models.CharField(choices=[('PTN', 'Procurador'), ('SPTN', 'SubProcurador')], default='PTN', max_length=4)),
                ('activo', models.BooleanField(default=True)),
                ('tsbuscar', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resoluciones',
            },
        ),
    ]
